root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/ingest-server ./cmd/ingest-server"
bin = "./tmp/ingest-server"
include_dir = ["cmd", "internal", "pkg"]
exclude_file = ["_test.go"]

[run]
proxy = false
