/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaddedRouteImport } from './routes/_padded'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaddedUsersRouteImport } from './routes/_padded/users'
import { Route as PaddedStreamsRouteImport } from './routes/_padded/streams'
import { Route as PaddedSettingsRouteImport } from './routes/_padded/settings'
import { Route as PaddedLiveRouteImport } from './routes/_padded/live'
import { Route as PaddedVideoVideoIdRouteImport } from './routes/_padded/video.$videoId'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaddedRoute = PaddedRouteImport.update({
  id: '/_padded',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaddedUsersRoute = PaddedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedStreamsRoute = PaddedStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedSettingsRoute = PaddedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedLiveRoute = PaddedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedVideoVideoIdRoute = PaddedVideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => PaddedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/video': typeof VideoRoute
  '/live': typeof PaddedLiveRoute
  '/settings': typeof PaddedSettingsRoute
  '/streams': typeof PaddedStreamsRoute
  '/users': typeof PaddedUsersRoute
  '/video/$videoId': typeof PaddedVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/video': typeof VideoRoute
  '/live': typeof PaddedLiveRoute
  '/settings': typeof PaddedSettingsRoute
  '/streams': typeof PaddedStreamsRoute
  '/users': typeof PaddedUsersRoute
  '/video/$videoId': typeof PaddedVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_padded': typeof PaddedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/video': typeof VideoRoute
  '/_padded/live': typeof PaddedLiveRoute
  '/_padded/settings': typeof PaddedSettingsRoute
  '/_padded/streams': typeof PaddedStreamsRoute
  '/_padded/users': typeof PaddedUsersRoute
  '/_padded/video/$videoId': typeof PaddedVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/video'
    | '/live'
    | '/settings'
    | '/streams'
    | '/users'
    | '/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/video'
    | '/live'
    | '/settings'
    | '/streams'
    | '/users'
    | '/video/$videoId'
  id:
    | '__root__'
    | '/'
    | '/_padded'
    | '/login'
    | '/setup'
    | '/video'
    | '/_padded/live'
    | '/_padded/settings'
    | '/_padded/streams'
    | '/_padded/users'
    | '/_padded/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaddedRoute: typeof PaddedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_padded': {
      id: '/_padded'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PaddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_padded/users': {
      id: '/_padded/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PaddedUsersRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/streams': {
      id: '/_padded/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof PaddedStreamsRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/settings': {
      id: '/_padded/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PaddedSettingsRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/live': {
      id: '/_padded/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof PaddedLiveRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/video/$videoId': {
      id: '/_padded/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof PaddedVideoVideoIdRouteImport
      parentRoute: typeof PaddedRoute
    }
  }
}

interface PaddedRouteChildren {
  PaddedLiveRoute: typeof PaddedLiveRoute
  PaddedSettingsRoute: typeof PaddedSettingsRoute
  PaddedStreamsRoute: typeof PaddedStreamsRoute
  PaddedUsersRoute: typeof PaddedUsersRoute
  PaddedVideoVideoIdRoute: typeof PaddedVideoVideoIdRoute
}

const PaddedRouteChildren: PaddedRouteChildren = {
  PaddedLiveRoute: PaddedLiveRoute,
  PaddedSettingsRoute: PaddedSettingsRoute,
  PaddedStreamsRoute: PaddedStreamsRoute,
  PaddedUsersRoute: PaddedUsersRoute,
  PaddedVideoVideoIdRoute: PaddedVideoVideoIdRoute,
}

const PaddedRouteWithChildren =
  PaddedRoute._addFileChildren(PaddedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaddedRoute: PaddedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
