/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaddedRouteImport } from './routes/_padded'
import { Route as PaddedIndexRouteImport } from './routes/_padded.index'
import { Route as VideoVideoIdRouteImport } from './routes/video.$videoId'
import { Route as PaddedUsersRouteImport } from './routes/_padded.users'
import { Route as PaddedStreamsRouteImport } from './routes/_padded.streams'
import { Route as PaddedSettingsRouteImport } from './routes/_padded.settings'
import { Route as PaddedLiveRouteImport } from './routes/_padded.live'
import { Route as PaddedLibrariesRouteImport } from './routes/_padded.libraries'
import { Route as LibrariesLibraryIdIndexRouteImport } from './routes/libraries.$libraryId.index'
import { Route as LibrariesLibraryIdVideoVideoIdRouteImport } from './routes/libraries.$libraryId.video.$videoId'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaddedRoute = PaddedRouteImport.update({
  id: '/_padded',
  getParentRoute: () => rootRouteImport,
} as any)
const PaddedIndexRoute = PaddedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaddedRoute,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => VideoRoute,
} as any)
const PaddedUsersRoute = PaddedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedStreamsRoute = PaddedStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedSettingsRoute = PaddedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedLiveRoute = PaddedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => PaddedRoute,
} as any)
const PaddedLibrariesRoute = PaddedLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => PaddedRoute,
} as any)
const LibrariesLibraryIdIndexRoute = LibrariesLibraryIdIndexRouteImport.update({
  id: '/libraries/$libraryId/',
  path: '/libraries/$libraryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdVideoVideoIdRoute =
  LibrariesLibraryIdVideoVideoIdRouteImport.update({
    id: '/libraries/$libraryId/video/$videoId',
    path: '/libraries/$libraryId/video/$videoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/video': typeof VideoRouteWithChildren
  '/libraries': typeof PaddedLibrariesRoute
  '/live': typeof PaddedLiveRoute
  '/settings': typeof PaddedSettingsRoute
  '/streams': typeof PaddedStreamsRoute
  '/users': typeof PaddedUsersRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/': typeof PaddedIndexRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdIndexRoute
  '/libraries/$libraryId/video/$videoId': typeof LibrariesLibraryIdVideoVideoIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/video': typeof VideoRouteWithChildren
  '/libraries': typeof PaddedLibrariesRoute
  '/live': typeof PaddedLiveRoute
  '/settings': typeof PaddedSettingsRoute
  '/streams': typeof PaddedStreamsRoute
  '/users': typeof PaddedUsersRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/': typeof PaddedIndexRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdIndexRoute
  '/libraries/$libraryId/video/$videoId': typeof LibrariesLibraryIdVideoVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_padded': typeof PaddedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/video': typeof VideoRouteWithChildren
  '/_padded/libraries': typeof PaddedLibrariesRoute
  '/_padded/live': typeof PaddedLiveRoute
  '/_padded/settings': typeof PaddedSettingsRoute
  '/_padded/streams': typeof PaddedStreamsRoute
  '/_padded/users': typeof PaddedUsersRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/_padded/': typeof PaddedIndexRoute
  '/libraries/$libraryId/': typeof LibrariesLibraryIdIndexRoute
  '/libraries/$libraryId/video/$videoId': typeof LibrariesLibraryIdVideoVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/setup'
    | '/video'
    | '/libraries'
    | '/live'
    | '/settings'
    | '/streams'
    | '/users'
    | '/video/$videoId'
    | '/'
    | '/libraries/$libraryId'
    | '/libraries/$libraryId/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/video'
    | '/libraries'
    | '/live'
    | '/settings'
    | '/streams'
    | '/users'
    | '/video/$videoId'
    | '/'
    | '/libraries/$libraryId'
    | '/libraries/$libraryId/video/$videoId'
  id:
    | '__root__'
    | '/_padded'
    | '/login'
    | '/setup'
    | '/video'
    | '/_padded/libraries'
    | '/_padded/live'
    | '/_padded/settings'
    | '/_padded/streams'
    | '/_padded/users'
    | '/video/$videoId'
    | '/_padded/'
    | '/libraries/$libraryId/'
    | '/libraries/$libraryId/video/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PaddedRoute: typeof PaddedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  VideoRoute: typeof VideoRouteWithChildren
  LibrariesLibraryIdIndexRoute: typeof LibrariesLibraryIdIndexRoute
  LibrariesLibraryIdVideoVideoIdRoute: typeof LibrariesLibraryIdVideoVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_padded': {
      id: '/_padded'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PaddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_padded/': {
      id: '/_padded/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PaddedIndexRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof VideoRoute
    }
    '/_padded/users': {
      id: '/_padded/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PaddedUsersRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/streams': {
      id: '/_padded/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof PaddedStreamsRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/settings': {
      id: '/_padded/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PaddedSettingsRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/live': {
      id: '/_padded/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof PaddedLiveRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/_padded/libraries': {
      id: '/_padded/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof PaddedLibrariesRouteImport
      parentRoute: typeof PaddedRoute
    }
    '/libraries/$libraryId/': {
      id: '/libraries/$libraryId/'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/video/$videoId': {
      id: '/libraries/$libraryId/video/$videoId'
      path: '/libraries/$libraryId/video/$videoId'
      fullPath: '/libraries/$libraryId/video/$videoId'
      preLoaderRoute: typeof LibrariesLibraryIdVideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PaddedRouteChildren {
  PaddedLibrariesRoute: typeof PaddedLibrariesRoute
  PaddedLiveRoute: typeof PaddedLiveRoute
  PaddedSettingsRoute: typeof PaddedSettingsRoute
  PaddedStreamsRoute: typeof PaddedStreamsRoute
  PaddedUsersRoute: typeof PaddedUsersRoute
  PaddedIndexRoute: typeof PaddedIndexRoute
}

const PaddedRouteChildren: PaddedRouteChildren = {
  PaddedLibrariesRoute: PaddedLibrariesRoute,
  PaddedLiveRoute: PaddedLiveRoute,
  PaddedSettingsRoute: PaddedSettingsRoute,
  PaddedStreamsRoute: PaddedStreamsRoute,
  PaddedUsersRoute: PaddedUsersRoute,
  PaddedIndexRoute: PaddedIndexRoute,
}

const PaddedRouteWithChildren =
  PaddedRoute._addFileChildren(PaddedRouteChildren)

interface VideoRouteChildren {
  VideoVideoIdRoute: typeof VideoVideoIdRoute
}

const VideoRouteChildren: VideoRouteChildren = {
  VideoVideoIdRoute: VideoVideoIdRoute,
}

const VideoRouteWithChildren = VideoRoute._addFileChildren(VideoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PaddedRoute: PaddedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  VideoRoute: VideoRouteWithChildren,
  LibrariesLibraryIdIndexRoute: LibrariesLibraryIdIndexRoute,
  LibrariesLibraryIdVideoVideoIdRoute: LibrariesLibraryIdVideoVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
